# Generated by Django 4.2.28 on 2026-02-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': (['-created_on'],), 'verbose_name': ('Post',), 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
