# Generated by Django 4.2.28 on 2026-02-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': (['-created_on'],), 'verbose_name': ('Comment',), 'verbose_name_plural': 'Comments'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='commenter',
        ),
    ]
