# Generated by Django 4.2.28 on 2026-02-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': ('Post',), 'verbose_name_plural': 'Posts'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_on',
            new_name='created_onc',
        ),
    ]
