# Generated by Django 4.2.28 on 2026-02-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': ('Comment',), 'verbose_name_plural': ('Comments',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on'], 'verbose_name': ('Post',), 'verbose_name_plural': ('Posts',)},
        ),
        migrations.AlterOrderWithRespectTo(
            name='comment',
            order_with_respect_to=None,
        ),
    ]
