# Generated by Django 4.2.28 on 2026-02-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on'], 'verbose_name': ('Post',), 'verbose_name_plural': ('Posts',)},
        ),
    ]
