# Generated by Django 4.2.28 on 2026-02-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About the Developer', 'verbose_name_plural': 'About the Developers'},
        ),
    ]
