# Generated by Django 4.2.28 on 2026-02-27 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-created_on'], 'verbose_name': 'About the Developer', 'verbose_name_plural': 'About the Developers'},
        ),
    ]
