# Generated by Django 4.2.28 on 2026-02-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_collaboraterequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaboraterequest',
            options={'ordering': ['created_on'], 'verbose_name': 'Collaboration Request', 'verbose_name_plural': 'Collaboration Requests'},
        ),
        migrations.AlterField(
            model_name='collaboraterequest',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
