# Generated by Django 4.2.28 on 2026-02-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_collaboraterequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboraterequest',
            name='message',
            field=models.TextField(unique=True),
        ),
    ]
