# Generated by Django 4.2.28 on 2026-03-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_collaboraterequest_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollaborateRequest',
            new_name='Collaborate',
        ),
    ]
